org: choliveira
app: aws-event-demo
custom: ${file(serverless/config/custom.yml)}
service: ${self:custom.service}
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${self:custom.stage, self:custom.defaultStage}
  region: ${self:custom.region}
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  architecture: arm64
  timeout: 30
  logs:
    restApi: true
  iamRoleStatements:
    - ${file(serverless/resources/iam/payment-table-iam.yml):payment-table-iam}

functions:
  - ${file(serverless/resources/lambda/post-payment.yml)}

resources:
  Resources:
    paymentTable: ${file(serverless/resources/dynamo/payment-table.yml):paymentTable}

useDotenv: true
