org: choliveira
app: aws-event-demo
custom: ${file(serverless/config/custom.yml)}
service: ${self:custom.service}
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${self:custom.stage, self:custom.defaultStage}
  region: ${self:custom.region}
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    ACCESS_KEY: ${param:ACCESS_KEY, env:ACCESS_KEY}
    SECRET_ACCESS_KEY: ${param:SECRET_ACCESS_KEY, env:SECRET_ACCESS_KEY}
  architecture: arm64
  timeout: 30
  logs:
    restApi: true
  iamRoleStatements:
    - ${file(serverless/resources/iam/payment-table-iam.yml):payment-table-iam}
    - ${file(serverless/resources/iam/order-table-iam.yml):order-table-iam}
    - ${file(serverless/resources/iam/process-order-created-queue-iam.yml):process-order-created-queue-iam}

functions:
  - ${file(serverless/resources/lambda/post-payment.yml)}
  - ${file(serverless/resources/lambda/post-order.yml)}
  - ${file(serverless/resources/lambda/order-stream.yml)}
  - ${file(serverless/resources/lambda/delivery-service.yml)}

resources:
  Resources:
    paymentTable: ${file(serverless/resources/dynamo/payment-table.yml):paymentTable}
    orderTable: ${file(serverless/resources/dynamo/order-table.yml):orderTable}
    processOrderCreated:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: 'process-order-created'

useDotenv: true
